[fr-FR] Correction of several errors in the various files
Sasino97/gta-cnr-localization pull request #74
Opened 2024-08-10 09:31 UTC by ImWarzox

2024-08-11 20:00 UTC, TanyoushkaA commented on vehicles.xml
> +        <String xml:lang="fr-FR">Saisir le modèle, la marque ou la plaque d'immatriculation du véhicule.</String>
Previous translation fits better

2024-08-21 13:38 UTC, stijnjw requested changes
Please fix feedback given by the other translator

2024-08-27 22:19 UTC, stijnjw approved these changes

2024-08-27 22:46 UTC, stijnjw approved these changes

2024-08-27 22:46 UTC, merged